---
title: "collaborator analysis"
author: "Bailey Morrison"
format: html
---

## Exercise: Explore, Clean, and Wrangle Data
```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
```

```{r}
lobster_traps <- read_csv("../data/Lobster_Trap_Counts_All_Years_20210519.csv")
```

```{r}
glimpse(lobster_traps)
```

```{r}
lobster_traps = lobster_traps %>%
  mutate(TRAPS = na_if(TRAPS, -99999))
```

## Exercise: Data Visualization
```{r}
#| warning: false
#| message: false

facet_plot <- ggplot(data = lobster_traps, aes(x = TRAPS))+
  geom_histogram()+
  facet_wrap(~YEAR,ncol = 5, nrow = 2)+
  theme_bw()+
  labs(x = "# Traps", y = "Frequency")
facet_plot
```

```{r}
lobsters_traps_summarize <- lobster_traps %>% 
  group_by(SITE, YEAR) %>% 
  summarize(TOTAL_TRAPS = sum(TRAPS, na.rm = TRUE))

ggplot(data = lobsters_traps_summarize, aes(x = YEAR, y = TOTAL_TRAPS, linetype = SITE)) +
    geom_point(aes(color = SITE)) +
    geom_line(aes(color = SITE))+
  labs(x = "Year", y = "Total Traps")+
  ggtitle("Observed Lobster Traps Over Time")+
  theme_light()+
  scale_x_continuous(breaks = 2012:2021, labels = 2012:2021)+
  theme(axis.title = element_text(size = 12, face = "bold"),
        legend.title = element_text(size = 12, face = 'bold'),
        plot.title = element_text(size = 14, face = 'bold'))
```


